server:
  port: 5208
  servlet:
    context-path: /yf-blog/
logging:
  config: classpath:log4j2.xml

spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.auto_quote_keyword: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: